title: "LIFFもいいけどリッチメニューを触ってみよう！"
summary: ""
topics: []
published: false
price: 0
# 本に含めるチャプターを順番に並べましょう
chapters:
  - description
  - before-input
  - how-to-use-rich-menu
  - why-rich-menu
  - liff-vs-rich-menu
  - setup
  - handson
  - after-input
  - create-rich-menu
  - user-link